version: 2
jobs:

  test-unit:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout:
          path:
            "bxrelay"
      - add_ssh_keys:
          fingerprints:
            "36:c1:e1:3e:e9:c6:c6:4b:8e:54:b1:34:ae:9a:ae:ad"
      - git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: # run tests
          name: Tests
          command: |
            . venv/bin/activate
            PYLINTRC_PATH=bxcommon/pylintrc python -m unittest discover -s bxrelay/test -t bxrelay/test --verbose
      - store_artifacts: # special step to store test reports as artifacts
          path: test-reports/
          destination: tr1

  build:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - run:
          name: Package
          command: 'echo "Yay develop build!"'

  build-prod:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - run:
          name: Package
          command: 'echo "Yay master build!"'

workflows:
  version: 2

  test-build:
    jobs:
      - test-unit
      - build:
          requires:
            - test-unit
          filters:
            branches:
              only: develop

      - build-prod:
          requires:
            - test-unit
          filters:
            branches:
              only: master
